name: K_PSF
channels:
        - pytorch
        - nvidia
        - anaconda
        - iopath
        - defaults
dependencies:
        - python=3.10
        - pip=22.3.1
        - pytorch=1.10.0
        - cudatoolkit=11.3
        - torchvision
        - iopath
        - pip:
            - fvcore
            - open3d
            - gdown
            - trimesh
            - scipy
            - ninja
            - POT